export const SKILL_LIST = [
  // --- Technology & Development ---
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C#",
  "C++",
  "Ruby",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "PHP",
  "Scala",
  "Haskell",
  "Lua",
  "Perl",
  "R",
  "MATLAB",
  "Dart",
  "HTML5",
  "CSS3",
  // Frontend Frameworks & Libraries
  "React",
  "Angular",
  "Vue.js",
  "Svelte",
  "Next.js",
  "Gatsby",
  "Nuxt.js",
  "Redux",
  "MobX",
  "jQuery",
  "Tailwind CSS",
  "Bootstrap",
  "Sass/SCSS",
  "Material-UI",
  "Webpack",
  "Vite",
  // Backend Frameworks & Libraries
  "Node.js",
  "Express.js",
  "NestJS",
  "Django",
  "Flask",
  "FastAPI",
  "Ruby on Rails",
  "Spring Boot",
  "ASP.NET",
  "Laravel",
  "Phoenix (Elixir)",
  // Databases & Data Storage
  "SQL",
  "PostgreSQL",
  "MySQL",
  "Microsoft SQL Server",
  "Oracle",
  "SQLite",
  "MariaDB",
  "NoSQL",
  "MongoDB",
  "Redis",
  "Cassandra",
  "CouchDB",
  "Neo4j (Graph DB)",
  "Elasticsearch",
  // Cloud & DevOps
  "AWS (Amazon Web Services)",
  "Microsoft Azure",
  "Google Cloud Platform (GCP)",
  "Docker",
  "Kubernetes",
  "Terraform",
  "Ansible",
  "Puppet",
  "Chef",
  "CI/CD",
  "Jenkins",
  "GitLab CI",
  "GitHub Actions",
  "CircleCI",
  "Serverless Architecture",
  "AWS Lambda",
  "Azure Functions",
  "Google Cloud Functions",
  "Microservices Architecture",
  "Linux Administration",
  "Bash Scripting",
  "NGINX",
  "Apache",
  // Mobile Development
  "iOS Development",
  "Android Development",
  "React Native",
  "Flutter",
  "Xamarin",
  "NativeScript",
  "Ionic",
  // Data Science & Machine Learning
  "Data Analysis",
  "Data Visualization",
  "Machine Learning",
  "Deep Learning",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Reinforcement Learning",
  "Pandas",
  "NumPy",
  "SciPy",
  "Scikit-learn",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Matplotlib",
  "Seaborn",
  "Jupyter Notebooks",
  "Apache Spark",
  "Hadoop",
  "ETL Processes",
  // Software Testing & QA
  "Manual Testing",
  "Automated Testing",
  "Performance Testing",
  "Security Testing",
  "Unit Testing",
  "Integration Testing",
  "End-to-End (E2E) Testing",
  "Selenium",
  "Cypress",
  "Playwright",
  "Jest",
  "Mocha",
  "PyTest",
  "JMeter",
  // Web3 & Blockchain
  "Blockchain",
  "Ethereum",
  "Solidity",
  "Smart Contract Development",
  "Web3.js",
  "Ethers.js",
  "Hardhat",
  "Truffle",
  "IPFS",
  "DeFi (Decentralized Finance)",
  "NFT (Non-Fungible Tokens)",
  // Misc Tech
  "APIs",
  "REST APIs",
  "GraphQL",
  "gRPC",
  "WebSockets",
  "Cybersecurity",
  "Ethical Hacking",
  "Penetration Testing",
  "Network Security",
  "WebRTC",
  "AR (Augmented Reality)",
  "VR (Virtual Reality)",
  "Unity",
  "Unreal Engine",
  "Godot Engine",
  "Game Development",
  "IoT (Internet of Things)",
  "Raspberry Pi",
  "Arduino",
  "WordPress Development",
  "Webflow",
  "Systems Design",
  "Algorithm Design",

  // --- Creative & Design ---
  "Graphic Design",
  "UI (User Interface) Design",
  "UX (User Experience) Design",
  "Interaction Design",
  "Information Architecture",
  "User Research",
  "Usability Testing",
  "Design Systems",
  "Figma",
  "Adobe XD",
  "Sketch",
  "Canva",
  "Procreate",
  "Photoshop",
  "Illustrator",
  "InDesign",
  "Affinity Designer",
  "Video Editing",
  "Premiere Pro",
  "Final Cut Pro",
  "DaVinci Resolve",
  "After Effects",
  "Motion Graphics",
  "Animation",
  "2D Animation",
  "3D Animation",
  "3D Modeling",
  "Blender",
  "ZBrush",
  "Cinema 4D",
  "CAD",
  "Photography",
  "Portrait Photography",
  "Landscape Photography",
  "Photo Editing",
  "Lightroom",
  "Illustration",
  "Digital Painting",
  "Character Design",
  "Logo Design",
  "Brand Identity Design",
  "Typography",
  "Color Theory",
  "Color Grading",
  "Copywriting",
  "UX Writing",
  "Creative Writing",
  "Technical Writing",
  "Scriptwriting",
  "Content Creation",
  "Blogging",
  "Podcasting",
  "Audio Engineering",
  "Audio Editing",
  "Audacity",
  "Logic Pro X",
  "Ableton Live",
  "FL Studio",
  "Music Production",
  "Sound Design",
  "Foley Artistry",
  "Videography",
  "Cinematography",
  "Storyboarding",
  "Voice Acting",

  // --- Business & Professional ---
  "Project Management",
  "Product Management",
  "Agile Methodologies",
  "Scrum Master",
  "Kanban",
  "Jira",
  "Asana",
  "Trello",
  "Business Analysis",
  "Business Strategy",
  "Business Development",
  "Digital Marketing",
  "SEO (Search Engine Optimization)",
  "SEM (Search Engine Marketing)",
  "PPC Advertising",
  "Content Marketing",
  "Social Media Marketing",
  "Email Marketing",
  "Affiliate Marketing",
  "Google Analytics",
  "Google Tag Manager",
  "HubSpot",
  "Marketo",
  "A/B Testing",
  "Conversion Rate Optimization (CRO)",
  "Data-Driven Decision Making",
  "Excel",
  "Advanced Excel (VBA)",
  "Google Sheets",
  "PowerPoint",
  "Keynote",
  "Google Slides",
  "Public Speaking",
  "Presentation Skills",
  "Sales",
  "Lead Generation",
  "Negotiation",
  "Customer Relationship Management (CRM)",
  "Salesforce",
  "Human Resources (HR)",
  "Recruiting",
  "Talent Management",
  "Employee Relations",
  "Financial Analysis",
  "Financial Modeling",
  "Bookkeeping",
  "Accounting",
  "QuickBooks",
  "Xero",
  "Market Research",
  "Competitive Analysis",
  "Leadership",
  "Team Management",
  "Operations Management",
  "Supply Chain Management",
  "Logistics",
  "E-commerce Management",
  "Shopify",
  "Amazon FBA",
  "Grant Writing",
  "Legal Research",
  "Contract Law",
  "Intellectual Property Law",
  "Startup Mentorship",
  "Venture Capital Analysis",
  "Risk Management",
  "Quality Assurance",

  // --- Practical & Lifestyle Skills ---
  "Cooking",
  "Baking",
  "Sourdough Baking",
  "Pastry Making",
  "Meal Prep",
  "Mixology (Cocktail Making)",
  "Barista Skills",
  "Coffee Brewing",
  "Wine Tasting",
  "Fermentation (Kimchi, Kombucha)",
  "Gardening",
  "Hydroponics",
  "Home Repair",
  "Plumbing Basics",
  "Electrical Basics",
  "Carpentry",
  "Woodworking",
  "Furniture Assembly",
  "Car Maintenance",
  "Bicycle Repair",
  "Knitting",
  "Crocheting",
  "Sewing",
  "Embroidery",
  "Drawing",
  "Painting (Watercolor, Acrylic, Oil)",
  "Calligraphy",
  "Pottery",
  "Ceramics",
  "Origami",
  "Jewelry Making",
  "Candle Making",
  "Soap Making",
  "Guitar",
  "Ukulele",
  "Piano",
  "Violin",
  "Drums",
  "Bass Guitar",
  "Singing",
  "Songwriting",
  "DJing",
  "Yoga Instruction",
  "Pilates Instruction",
  "Personal Training",
  "Meditation Guidance",
  "Mindfulness Coaching",
  "Nutrition Planning",
  "Event Planning",
  "Wedding Planning",
  "Interior Design",
  "Feng Shui",
  "Minimalism Coaching",
  "Organization (KonMari method)",
  "Pet Training",
  "Dog Grooming",
  "First Aid & CPR",
  "Survival Skills",
  "Astrology Reading",
  "Tarot Card Reading",
  "Magic Tricks",
  "Improvisation",
  "Stand-up Comedy",

  // --- Languages & Tutoring ---
  "English",
  "Spanish",
  "French",
  "German",
  "Mandarin Chinese",
  "Japanese",
  "Korean",
  "Italian",
  "Arabic",
  "Portuguese",
  "Russian",
  "Hindi",
  "Bengali",
  "Dutch",
  "Swedish",
  "Turkish",
  "Vietnamese",
  "American Sign Language (ASL)",
  "Proofreading",
  "Editing",
  "Translation",
  "Transcription",
  "Math Tutoring (Algebra, Calculus, etc.)",
  "Physics Tutoring",
  "Chemistry Tutoring",
  "Biology Tutoring",
  "History Tutoring",
  "Economics Tutoring",
  "Philosophy Tutoring",
  "Test Prep (SAT, ACT, GRE, etc.)",
  "Resume Writing",
  "Cover Letter Writing",
  "LinkedIn Profile Optimization",
  "Interview Coaching"
];