// src/skills.js
export const users = [
  {
    name: 'Mohan Aggarwal',
    location: 'Mumbai, Maharashtra',
    status: 'Available',
    isPro: true,
    lastSeen: '2 hours ago',
    rating: 4.9,
    offering: ['React', 'TypeScript', 'Node.js'],
    lookingFor: ['Python', 'Machine Learning', 'Data Science'],
    description: 'Full-stack developer passionate about modern web technologies. Looking to expand into AI/ML.',
    swaps: 23,
    responseRate: '95%',
    avatar: 'MA',
  },
  {
    name: 'Priya Sharma',
    location: 'Delhi, India',
    status: 'Busy',
    isPro: false,
    lastSeen: '1 day ago',
    rating: 4.8,
    offering: ['Python', 'Django', 'PostgreSQL'],
    lookingFor: ['React', 'GraphQL', 'AWS'],
    description: 'Backend engineer with 5+ years experience. Eager to learn modern frontend frameworks.',
    swaps: 31,
    responseRate: '88%',
    avatar: 'PS',
  },
  {
    name: 'Arjun Patel',
    location: 'Bangalore, Karnataka',
    status: 'Available',
    isPro: true,
    lastSeen: '30 minutes ago',
    rating: 5,
    offering: ['UX Design', 'Figma', 'User Research'],
    lookingFor: ['React', 'CSS', 'Animation'],
    description: 'UX designer transitioning to frontend development. Love creating beautiful user experiences.',
    swaps: 18,
    responseRate: '100%',
    avatar: 'AP',
  },
  {
    name: 'Rajesh Kumar',
    location: 'Hyderabad, Telangana',
    status: 'Available',
    lastSeen: '5 hours ago',
    rating: 4.7,
    offering: ['Java', 'Spring Boot', 'Microservices'],
    lookingFor: ['Go', 'Kubernetes', 'Docker'],
    description: 'Senior backend developer looking to modernize my tech stack with cloud-native technologies.',
    swaps: 42,
    responseRate: '92%',
    avatar: 'RK',
  },
  {
    name: 'Anita Singh',
    location: 'Pune, Maharashtra',
    status: 'Busy',
    isPro: true,
    lastSeen: '1 hour ago',
    rating: 4.9,
    offering: ['iOS', 'Swift', 'SwiftUI'],
    lookingFor: ['React Native', 'Flutter', 'Kotlin'],
    description: 'Mobile developer specializing in iOS. Want to expand to cross-platform development.',
    swaps: 27,
    responseRate: '97%',
    avatar: 'AS',
  },
  {
    name: 'Vikram Reddy',
    location: 'Chennai, Tamil Nadu',
    status: 'Available',
    lastSeen: '3 hours ago',
    rating: 4.6,
    offering: ['DevOps', 'AWS', 'Terraform'],
    lookingFor: ['Azure', 'GCP', 'Security'],
    description: 'DevOps engineer passionate about cloud infrastructure and automation.',
    swaps: 15,
    responseRate: '85%',
    avatar: 'VR',
  },
];